---
title: "Homework 6"
author: "J Shearston"
date: "November 26, 2018"
output: 
  github_document:
    toc: true
---


```{r setup, include=FALSE}

library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

```


## Problem 1: Washington Post Homicide Data

#### Loading and Tidying the Data 

```{r load and tidy homicide data, message = FALSE}

hom_data = read_csv("homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(city_state = str_c(city, ", ", state),
         solved = case_when(
           disposition == "Closed without arrest" ~ 0, 
           disposition == "Open/No arrest" ~ 0, 
           disposition == "Closed by arrest" ~ 1),
         notwhite_victim = case_when(
           victim_race == "Hispanic" ~ 1,
           victim_race == "White" ~ 0,
           victim_race == "Other" ~ 1,
           victim_race == "Black" ~ 1,
           victim_race == "Asian" ~ 1,
           victim_race == "NA" ~ 1)) %>% 
  filter(!city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))

```

#### Baltimore, MD

```{r glm for Baltimore}

baltimore_glm = 
  hom_data %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ notwhite_victim + victim_age + victim_sex, data = ., family = binomial()) %>%
  broom::tidy(conf.int = TRUE) %>% 
  mutate(OR = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high)) %>%
  filter(term == "notwhite_victim") %>% 
  select(term, OR, conf.low, conf.high) 

baltimore_glm %>% knitr::kable()

```

#### GLM for All Locations

```{r mapped glm}

hom_models = hom_data %>%
  group_by(city_state) %>% 
  nest() %>% 
  mutate(glm_results = map(data, ~broom::tidy(
    glm(solved ~ notwhite_victim + victim_age + victim_sex, data = ., family = binomial()),
    conf.int = TRUE))) %>%
  select(-data) %>% 
  unnest() %>% 
  mutate(OR = exp(estimate),
         conf.low = exp(conf.low),
         conf.high = exp(conf.high)) %>% 
  filter(term == "notwhite_victim") %>% 
  select(city_state, OR, conf.low, conf.high)
  
hom_models %>% knitr::kable()

```

#### Plot of OR and CIs for Each Location

```{r plot of ORs}

hom_models %>% 
  mutate(city_state = fct_reorder(city_state, OR),
         Significant = case_when(
           conf.high < 1 ~ 1,
           conf.high > 1 ~ 0),
         Significant = as.logical(Significant)) %>% 
  ggplot(aes(x = city_state, y = OR, color = Significant)) +
  geom_col() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  geom_hline(yintercept = 1) +
  labs(
    title = "Figure 1. Odds of Homicide Resolution, Non-white vs White Race",
    x = "Location",
    y = "Adjusted OR") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```


## Problem 2
